export const HeroSectionMainTitle = "Unify Your Market Intelligence. Empower Your Decisions."
export const HeroSectionSubInfo = "TG SuiteX brings every source of market insight—internal research, external data, and supplier intelligence—into one centralized, cloud-based platform."

export const KeyPointsTitle = "Unlock Clarity. Accelerate Decisions. Drive Growth."
export const KeyPointsInfo = "TG SuiteX empowers global enterprises to turn fragmented market data into actionable intelligence—helping every team move faster, smarter, and with confidence."
export const KeyPoint1 = "Unified Market Intelligence Platform – Access all internal and external data in one place."
export const KeyPoint2 = "Faster Decision-Making – Enable global teams to act instantly with shared insights."
export const KeyPoint3 = "Reduced Costs & Risk – Identify opportunities, optimize contracts, and manage volatility."
export const KeyPoint4 = "Collaborative Intelligence – Break silos across procurement, trading, and finance."
export const KeyPoint5 = "Enterprise-Grade Security – Protect your data with a robust, cloud-based architecture."

export const FooterHead = "It is a long established fact that from will be distracted by the readable from when looking."
export const FooterPageLink1 = "Home"
export const FooterPageLink2 = "About Us"
export const FooterPageLink3 = "Integrations"
export const FooterPageLink4 = "Features"
export const FooterPageLink5 = "Pricing"
export const FooterPageLink6 = "Contact Us"
export const FooterUtilityLink1 = "Integrations"
export const FooterUtilityLink2 = "Blog"
export const FooterUtilityLink3 = "Contact Us"
export const FooterUtilityLink4 = "Project Details"
export const FooterUtilityLink5 = "Pricing"
export const FooterUtilityLink6 = "Our Team"

export const LoginInfo = "Please enter your email and password"