export const HeroSectionMainTitlePart1 = "Powering Commodity Decisions with Unified Intelligence"
export const HeroSectionMainTitlePart2 = ""
export const HeroSectionSubInfo = "TG SuiteX empowers organizations to unify siloed data enabling to generate high-powered analytics, and insights across global teams—enabling smarter, faster, and more collaborative decision-making."

export const KeyPointsTitle = "Unlock Clarity. Accelerate Decisions. Drive Growth."
export const KeyPointsInfo = "TG SuiteX empowers global enterprises to turn fragmented market data into actionable intelligence—helping every team move faster, smarter, and with confidence."
export const KeyPoint1 = "Unified Commodity Intelligence Platform – Access all internal and external data in one place."
export const KeyPoint2 = "Faster Decision-Making – Enable global teams to act instantly with shared insights."
export const KeyPoint3 = "Reduced Costs & Risk – Identify opportunities, optimize contracts, and manage volatility."
export const KeyPoint4 = "Collaborative Intelligence – Break silos across procurement, trading, and finance."
export const KeyPoint5 = "Enterprise-Grade Security – Protect your data with a robust, cloud-based architecture."

export const FooterHead = ""
export const FooterPageLink1 = "About Us"
export const FooterPageLink2 = "Industries"
export const FooterPageLink3 = "Press Releases"
export const FooterPageLink4 = "Life at TransGraph"
export const FooterPageLink5 = "Brochures, Case Studies"
export const FooterPageLink6 = "Contact Us"
export const FooterUtilityLink1 = "TransRisk-Software"
export const FooterUtilityLink2 = "Price Consulting"
export const FooterUtilityLink3 = "Price Rish Management"
export const FooterUtilityLink4 = "Commodity Research"
export const FooterUtilityLink5 = "Business Consulting"

export const ProblemSolvingTitle = "Problems we are solving:"
export const ProblemSolving1 = "Scattered Data"
export const ProblemSolving2 = "Difficulty in Collaboration"
export const ProblemSolving3 = "Duplication of Data Subscription"
export const ProblemSolving4 = "Unawareness of Data Availability"
export const ProblemSolving5 = "Delayed Updates, Lost Opportunities"

export const BringTogetherSectionTitle = "How TG SuiteX Brings Every Insight Together"
export const BringTogetherSectionHead1 = "Identify your Data Sources"
export const BringTogetherSectionContent1 = "List down all your data Sources"
export const BringTogetherSectionHead2 = "Integrate with our Software"
export const BringTogetherSectionContent2 = "Through APIs/Excel store data Centrally"
export const BringTogetherSectionHead3 = "Access Centralized Data"
export const BringTogetherSectionContent3 = "Do Analysis and Share"

export const StrengthPointsTitle = "Centralize. Analyze. Monetize."
export const StrengthPointsContent = "TG SuiteX simplifies how global enterprises manage intelligence—turning complex data into confident decisions."
export const StrengthPoints1 = "One Source of Truth"
export const StrengthPoints2 = "Enhanced ROI on Data Subscriptions"
export const StrengthPoints3 = "Instant Collaboration"
export const StrengthPoints4 = "Analytics & Insights"
export const StrengthPoints5 = "Secure Cloud Access"
export const StrengthPoints6 = "Hosted on your Server"

export const LoginInfo = "Please enter your email and password"